import '../device/device_definition.dart';

/// Code Generator (WORK_V3 §41/§42)：
/// device.yaml (Source of Truth) → 多端代码。
///
/// 输出 (§41)：
/// ```text
/// generated/
/// ├── c/device_api.h         命令处理原型 (开发者实现硬件操作, §45)
/// ├── c/device_commands.c    命令路由 + 参数解析校验 (生成)
/// ├── c/device_state.h       状态结构体 (生成)
/// ├── dart/device_api.dart   强类型 Device API (生成)
/// ├── simulator/virtual_device.dart  虚拟设备骨架 (生成)
/// └── manifest.json          V3 格式 manifest (生成)
/// ```
///
/// 不生成 (§42)：main.c / startup / BLE driver / RTOS / HAL / Flash Driver
/// —— 由真实设备 SDK 提供。
class CodeGenerator {
  CodeGenerator._();

  /// 生成全部产物：相对路径 → 文件内容。
  static Map<String, String> generate(DeviceDefinition def) =>
      <String, String>{
        'c/device_api.h': _header(def),
        'c/device_api.c': _apiC(def),
        'c/device_commands.c': _commandsC(def),
        'c/device_state.h': _stateHeader(def),
        'dart/device_api.dart': _dartApi(def),
        'simulator/virtual_device.dart': _simulator(def),
        'manifest.json': _manifest(def),
      };

  /// c/device_api.c：命令处理 (参数解析校验 → 调用开发者硬件函数)。
  /// 开发者不需要修改本文件；实现 device_app.c 中 device_api.h 声明的函数即可。
  static String _apiC(DeviceDefinition def) {
    final buffer = StringBuffer()
      ..writeln('/**')
      ..writeln(' * Auto-generated by Device Platform Code Generator.')
      ..writeln(' * 命令处理：JSON 参数解析与校验 → 调用开发者硬件函数。')
      ..writeln(' * 开发者不需要修改本文件；实现 device_app.c 中的')
      ..writeln(' * device_api.h 声明的函数 (操作真实硬件, WORK_V3 §45)。')
      ..writeln(' */')
      ..writeln('#include "device_api.h"')
      ..writeln('#include <string.h>')
      ..writeln()
      ..writeln('/* §10.5 错误码 */')
      ..writeln('#define ERR_INVALID_PARAMETER 3001')
      ..writeln('#define ERR_UNKNOWN_COMMAND    3002')
      ..writeln()
      ..writeln('int device_handle_command(const char* cmd, const char* params_json,')
      ..writeln('                         char* response_json, int response_len) {');
    for (final command in def.commands) {
      final fn = _cFunctionName(command.name);
      buffer.writeln('  if (strcmp(cmd, "${command.name}") == 0) {');
      for (final entry in command.params.entries) {
        final name = entry.key;
        final type = entry.value.type;
        final min = entry.value.min;
        final max = entry.value.max;
        final cType = _cType(type);
        buffer
          ..writeln('    $cType $name;')
          ..writeln('    if (${_jsonGetter(type)}(params_json, "$name", &$name) != 0) {')
          ..writeln('      return ERR_INVALID_PARAMETER; // 缺字段或类型错误')
          ..writeln('    }');
        if (min != null && max != null && type != ValueType.boolType) {
          buffer
            ..writeln('    if ($name < $min || $name > $max) {')
            ..writeln('      return ERR_INVALID_PARAMETER; // 越界 [$min, $max]')
            ..writeln('    }');
        }
      }
      final args =
          command.params.keys.join(', ');
      buffer
        ..writeln('    return $fn($args, response_json, response_len);')
        ..writeln('  }');
    }
    buffer
      ..writeln('  return ERR_UNKNOWN_COMMAND;')
      ..writeln('}');
    return buffer.toString();
  }

  static String _commandsC(DeviceDefinition def) {
    final buffer = StringBuffer()
      ..writeln('/**')
      ..writeln(' * Auto-generated by Device Platform Code Generator.')
      ..writeln(' * 命令表 (SDK core 注册 / 日志使用)。命令处理见 device_api.c。')
      ..writeln(' */')
      ..writeln('#include <stddef.h>')
      ..writeln()
      ..writeln('typedef struct {')
      ..writeln('  const char* name;')
      ..writeln('} command_entry_t;')
      ..writeln()
      ..writeln('const command_entry_t g_commands[] = {');
    for (final command in def.commands) {
      buffer.writeln('  { "${command.name}" },');
    }
    buffer
      ..writeln('};')
      ..writeln()
      ..writeln('const unsigned g_command_count =')
      ..writeln('    (unsigned)(sizeof(g_commands) / sizeof(g_commands[0]));');
    return buffer.toString();
  }

  /// 类名：smart_light → SmartLight。
  static String _className(DeviceDefinition def) => def.id
      .split(RegExp(r'[_\-. ]'))
      .where((s) => s.isNotEmpty)
      .map((s) => s[0].toUpperCase() + s.substring(1))
      .join();

  /// C 函数名：light.set_power → light_set_power。
  static String _cFunctionName(String command) =>
      command.replaceAll('.', '_');

  static String _cType(ValueType type) => switch (type) {
        ValueType.boolType => 'bool',
        ValueType.uint8 => 'uint8_t',
        ValueType.uint16 => 'uint16_t',
        ValueType.int32 => 'int32_t',
        ValueType.float => 'float',
        ValueType.string => 'const char*',
      };

  static String _jsonGetter(ValueType type) => switch (type) {
        ValueType.boolType => 'device_json_get_bool',
        ValueType.uint8 || ValueType.uint16 || ValueType.int32 =>
          'device_json_get_uint',
        ValueType.float => 'device_json_get_float',
        ValueType.string => 'device_json_get_string',
      };

  /// c/device_api.h
  static String _header(DeviceDefinition def) {
    final buffer = StringBuffer()
      ..writeln('/**')
      ..writeln(' * Auto-generated by Device Platform Code Generator (WORK_V3 §41).')
      ..writeln(' * Source: device.yaml (${def.id})')
      ..writeln(' * DO NOT EDIT.')
      ..writeln(' *')
      ..writeln(' * 命令处理函数由开发者实现 (device_app.c / hardware.c, §45)：')
      ..writeln(' * 生成代码只负责协议路由与参数校验。')
      ..writeln(' */')
      ..writeln('#ifndef DEVICE_API_H')
      ..writeln('#define DEVICE_API_H')
      ..writeln()
      ..writeln('#include <stdbool.h>')
      ..writeln('#include <stdint.h>')
      ..writeln()
      ..writeln('/* 设备: ${def.name} (${def.model})，协议 v${def.protocolVersion}，API v${def.apiVersion} */')
      ..writeln();
    for (final command in def.commands) {
      final params = command.params.keys
          .map((name) => '${_cType(command.params[name]!.type)} $name')
          .join(', ');
      buffer.writeln(
        '/// ${command.name}：${params.isEmpty ? '无参数' : params}',
      );
      buffer.writeln('int ${_cFunctionName(command.name)}(');
      for (final entry in command.params.entries) {
        buffer.writeln(
          '    ${_cType(entry.value.type)} ${entry.key},',
        );
      }
      buffer.writeln('    char* response_json, int response_len);');
      buffer.writeln();
    }
    buffer
      ..writeln('/* 事件发布 (SDK 提供)：命令成功 / 状态变化后调用 */')
      ..writeln('void device_publish_event(const char* name, const char* json);')
      ..writeln()
      ..writeln('#endif /* DEVICE_API_H */');
    return buffer.toString();
  }

  /// c/device_state.h
  static String _stateHeader(DeviceDefinition def) {
    final buffer = StringBuffer()
      ..writeln('/** Auto-generated. 设备状态结构体 (WORK_V3 §37 状态模型)。 */')
      ..writeln('#ifndef DEVICE_STATE_H')
      ..writeln('#define DEVICE_STATE_H')
      ..writeln()
      ..writeln('#include <stdbool.h>')
      ..writeln('#include <stdint.h>')
      ..writeln()
      ..writeln('typedef struct {')
      ..writeln('  uint32_t version;');
    for (final entry in def.state.entries) {
      buffer.writeln('  ${_cType(entry.value.type)} ${entry.key};');
    }
    buffer
      ..writeln('} device_state_t;')
      ..writeln()
      ..writeln('/* SDK core 提供：状态变更后调用 (版本递增 + Patch 生成) */')
      ..writeln('void device_state_changed(const device_state_t* state);')
      ..writeln()
      ..writeln('#endif /* DEVICE_STATE_H */');
    return buffer.toString();
  }

  /// dart/device_api.dart
  static String _dartApi(DeviceDefinition def) {
    final className = _className(def);
    final stateClass = '${className}State';
    final buffer = StringBuffer()
      ..writeln('/// Auto-generated by Device Platform Code Generator.')
      ..writeln('/// Source: device.yaml (${def.id})。DO NOT EDIT。')
      ..writeln("import 'package:myhome/device/device_client.dart';")
      ..writeln("import 'package:myhome/protocol/protocol_messages.dart';")
      ..writeln()
      ..writeln('/// ${def.name} 强类型 Device API (§11)。')
      ..writeln('class ${className}Api {')
      ..writeln('  ${className}Api(this._client);')
      ..writeln()
      ..writeln('  final DeviceClient _client;')
      ..writeln();
    for (final command in def.commands) {
      // 方法名：light.set_power → lightSetPower (小驼峰)
      final parts = command.name.split(RegExp(r'[._]'));
      final methodName = parts
          .asMap()
          .entries
          .map((e) => e.key == 0
              ? e.value
              : e.value[0].toUpperCase() + e.value.substring(1))
          .join();
      final params = command.params.entries
          .map((e) => 'required ${_dartType(e.value.type)} ${e.key}')
          .join(', ');
      final map = command.params.keys
          .map((name) => "'$name': $name")
          .join(', ');
      buffer
        ..writeln('  /// ${command.name} (§10.2)')
        ..writeln('  Future<DeviceResponse> $methodName({$params}) =>')
        ..writeln("      _client.command('${command.name}', <String, dynamic>{$map});")
        ..writeln();
    }
    buffer
      ..writeln('}')
      ..writeln()
      ..writeln('/// ${def.name} 状态模型 (§16.1)。')
      ..writeln('class $stateClass {')
      ..writeln('  $stateClass.fromJson(Map<String, dynamic> json)');
    for (final entry in def.state.entries) {
      buffer.writeln(
        '      : ${entry.key} = ${_dartFromJson(entry.value.type, entry.key)},',
      );
    }
    buffer.writeln('        super();');
    buffer.writeln();
    for (final entry in def.state.entries) {
      buffer.writeln('  final ${_dartType(entry.value.type)} ${entry.key};');
    }
    buffer
      ..writeln('}')
      ..writeln();
    return buffer.toString();
  }

  static String _dartType(ValueType type) => switch (type) {
        ValueType.boolType => 'bool',
        ValueType.uint8 || ValueType.uint16 || ValueType.int32 => 'int',
        ValueType.float => 'double',
        ValueType.string => 'String',
      };

  static String _dartFromJson(ValueType type, String key) => switch (type) {
        ValueType.boolType => "json['$key'] as bool",
        ValueType.uint8 || ValueType.uint16 || ValueType.int32 =>
          "(json['$key'] as num).toInt()",
        ValueType.float => "(json['$key'] as num).toDouble()",
        ValueType.string => "json['$key'] as String",
      };

  /// simulator/virtual_device.dart
  static String _simulator(DeviceDefinition def) {
    final className = '${_className(def)}VirtualDevice';
    final buffer = StringBuffer()
      ..writeln('/// Auto-generated by Device Platform Code Generator.')
      ..writeln('/// Source: device.yaml (${def.id})。')
      ..writeln('///')
      ..writeln('/// 骨架已含协议接线与参数校验；TODO 处接入你的业务逻辑')
      ..writeln('/// (Device Logic + Virtual Hardware, WORK_V3 §27)。')
      ..writeln("import 'package:myhome/device/protocol_device.dart';")
      ..writeln("import 'package:myhome/protocol/protocol_messages.dart';")
      ..writeln()
      ..writeln('class $className extends ProtocolDevice {')
      ..writeln('  @override')
      ..writeln("  String get deviceId => '${def.id}';")
      ..writeln()
      ..writeln('  @override')
      ..writeln("  String get name => '${def.name}';")
      ..writeln()
      ..writeln('  @override')
      ..writeln("  String get uiVersion => '0.1.0'; // TODO: 与 UI 包版本同步")
      ..writeln()
      ..writeln('  @override')
      ..writeln('  DeviceHelloAck helloAckFor(DeviceHello hello) => DeviceHelloAck(')
      ..writeln('        requestId: hello.requestId,')
      ..writeln('        protocolVersion: ${def.protocolVersion},')
      ..writeln("        deviceType: '${def.id}',")
      ..writeln("        deviceModel: '${def.model}',")
      ..writeln("        firmwareVersion: '0.1.0',")
      ..writeln('        uiVersion: uiVersion,')
      ..writeln('        capabilities: const <String>[');
    for (final key in def.state.keys) {
      buffer.writeln("          '$key',");
    }
    buffer
      ..writeln('        ],')
      ..writeln('      );')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Future<void> onDeviceConnect() async {')
      ..writeln('    // TODO: 推送初始状态 (状态版本从 1 开始)')
      ..writeln('    pushState(DeviceState(version: 1, state: <String, dynamic>{}));')
      ..writeln('  }')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Future<void> onDeviceDisconnect() async {}')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  DeviceState get currentState =>')
      ..writeln('      const DeviceState(version: 1, state: <String, dynamic>{}); // TODO')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Future<DeviceResponse?> handleCommand(DeviceCommand command) async {')
      ..writeln('    switch (command.cmd) {');
    for (final command in def.commands) {
      buffer.writeln("      case '${command.name}':");
      for (final entry in command.params.entries) {
        final name = entry.key;
        final type = entry.value.type;
        final check = switch (type) {
          ValueType.boolType => "command.params['$name'] is! bool",
          ValueType.uint8 || ValueType.uint16 || ValueType.int32 =>
            "command.params['$name'] is! num",
          ValueType.float => "command.params['$name'] is! num",
          ValueType.string => "command.params['$name'] is! String",
        };
        buffer.writeln('        if ($check) {');
        buffer.writeln('          return DeviceResponse(');
        buffer.writeln('            requestId: command.requestId,');
        buffer.writeln("            status: 'error',");
        buffer.writeln("            error: const DeviceError(code: 3001, message: 'invalid $name'),");
        buffer.writeln('          );');
        buffer.writeln('        }');
      }
      buffer
        ..writeln('        // TODO: 业务逻辑 (操作 Virtual Hardware)')
        ..writeln('        return DeviceResponse(')
        ..writeln('          requestId: command.requestId,')
        ..writeln('          data: const <String, dynamic>{},')
        ..writeln('        );');
    }
    buffer
      ..writeln('      default:')
      ..writeln('        return DeviceResponse(')
      ..writeln('          requestId: command.requestId,')
      ..writeln("          status: 'error',")
      ..writeln("          error: DeviceError(code: 3002, message: 'unknown command'),")
      ..writeln('        );')
      ..writeln('    }')
      ..writeln('  }')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Uint8List? resourceBytes(String path) => null; // TODO: UI 包')
      ..writeln('}');
    return buffer.toString();
  }

  /// manifest.json (V3 格式, FRAMEWORK_V3 §9)。
  static String _manifest(DeviceDefinition def) {
    final type = def.id; // V3 manifest device.type 与 device.yaml id 对应 (执行决策)
    final buffer = StringBuffer()
      ..writeln('{')
      ..writeln('  "package": "${type}_ui",')
      ..writeln('  "version": "0.1.0",')
      ..writeln('  "device": {')
      ..writeln('    "type": "$type",')
      ..writeln('    "model": "${def.model}"')
      ..writeln('  },')
      ..writeln('  "protocol": {')
      ..writeln('    "version": ${def.protocolVersion}')
      ..writeln('  },')
      ..writeln('  "entry": "index.html",')
      ..writeln('  "api_version": ${def.apiVersion},')
      ..writeln('  "capabilities": [');
    final keys = def.state.keys.toList();
    for (var i = 0; i < keys.length; i++) {
      buffer.writeln('    "${keys[i]}"${i == keys.length - 1 ? '' : ','}');
    }
    buffer
      ..writeln('  ]')
      ..writeln('}');
    return buffer.toString();
  }
}
